/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.17
 * Generated at: 2019-05-13 09:52:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class CreateCompany_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/Users/xiaoluo/eclipse-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ISST-19-CRIS/WEB-INF/lib/standard-1.1.2.jar!/META-INF/fn.tld", Long.valueOf(1098703890000L));
    _jspx_dependants.put("jar:file:/Users/xiaoluo/eclipse-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ISST-19-CRIS/WEB-INF/lib/shiro-web-1.4.0.jar!/META-INF/shiro.tld", Long.valueOf(1494006348000L));
    _jspx_dependants.put("/WEB-INF/lib/shiro-web-1.4.0.jar", Long.valueOf(1553598958492L));
    _jspx_dependants.put("jar:file:/Users/xiaoluo/eclipse-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ISST-19-CRIS/WEB-INF/lib/standard-1.1.2.jar!/META-INF/c.tld", Long.valueOf(1098703890000L));
    _jspx_dependants.put("/WEB-INF/lib/standard-1.1.2.jar", Long.valueOf(1553598963966L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("   <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("   <title>Create Company</title>\n");
      out.write("   <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\" integrity=\"sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u\" crossorigin=\"anonymous\">\n");
      out.write("<!-- Temas-->\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css\" integrity=\"sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp\" crossorigin=\"anonymous\">\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<style type=\"text/css\">\n");
      out.write("body {\n");
      out.write("\tbackground-image:\n");
      out.write("\t\turl('https://image.jimcdn.com/app/cms/image/transf/none/path/sc77e1e58a42c514a/image/i9977c7b3a6db203a/version/1516578954/image.jpg');\n");
      out.write("\tbackground-size: cover;\n");
      out.write("\tfont: normal normal 16px quicksand; \n");
      out.write("\tletter-spacing: 1px;\n");
      out.write("\t\n");
      out.write("\ttext-align: center;\n");
      out.write("\ttext-transform: uppercase;\n");
      out.write("    background-position: center;\n");
      out.write("    background-repeat: no-repeat;\n");
      out.write("    overflow-x: hidden;\n");
      out.write("    padding-top: 20px;\n");
      out.write("    z-index: 1;\n");
      out.write("    top: 0;\n");
      out.write("    left: 0;\n");
      out.write("    \n");
      out.write("}\n");
      out.write("h1 {\n");
      out.write("text-align: center;\n");
      out.write("padding: 13vh;\n");
      out.write("  font-weight: normal;\n");
      out.write("  font-size: 40px;\n");
      out.write("  font-family: 'Lobster';\n");
      out.write("  text-transform: uppercase;    \n");
      out.write("}\n");
      out.write("div{\n");
      out.write("     font-size: medium;\n");
      out.write("     font-family: 'Lobster';\n");
      out.write("     font-weight: bold;\n");
      out.write("}\n");
      out.write("input[type=\"submit\"] {\n");
      out.write("\tborder-color: #7A9B1B2;\n");
      out.write("\tborder-radius: 25px;\n");
      out.write("\tbackground-color: #A9B1B2;\n");
      out.write("\tfont-size: medium;\n");
      out.write("\tfont-family: 'Lobster';\n");
      out.write("\tfont-weight: bold;\n");
      out.write("}\n");
      out.write("#Contenedor{\n");
      out.write("\twidth: 400px;\n");
      out.write("\tmargin: 50px auto;\n");
      out.write("\tbackground-color: #F3EDED;\n");
      out.write("        border: 15px solid #ECE8E8;\n");
      out.write("\theight: 300px;\n");
      out.write("\tborder-radius:8px;\n");
      out.write("\tpadding: 0px 9px 0px 9px;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("<body>\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "NavBar.jsp", out, false);
      out.write("\n");
      out.write("\t<h1>Completa con los datos de su empresa:</h1>\n");
      out.write("\t\t<div id=\"Contenedor\">\n");
      out.write("<div class=\"ContentForm\">\n");
      out.write("\t\t<form action=\"SignUpCompanyServlet\" method=\"post\">\n");
      out.write("\t\t<div class=\"input-group input-group-lg\">\n");
      out.write("\t\t<span class=\"input-group-addon\" id=\"sizing-addon1\"></span>\n");
      out.write("\t\t\t\t  <input type=\"text\" class=\"form-control\" name=\"email\" placeholder=\"Correo\" id=\"email\" aria-describedby=\"sizing-addon1\" required>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t<br>\n");
      out.write("\t\t\t\t<div class=\"input-group input-group-lg\">\n");
      out.write("\t\t\t\t  <span class=\"input-group-addon\" id=\"sizing-addon1\"></span>\n");
      out.write("\t\t\t\t  <input type=\"password\" name=\"password\" class=\"form-control\" placeholder=\"password\" aria-describedby=\"sizing-addon1\" required>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t<br>\n");
      out.write("\t\t\t\t<div class=\"input-group input-group-lg\">\n");
      out.write("\t\t\t\t  <span class=\"input-group-addon\" id=\"sizing-addon1\"></span>\n");
      out.write("\t\t\t\t  <input type=\"text\" name=\"nombre\" class=\"form-control\" placeholder=\"Nombre\" aria-describedby=\"sizing-addon1\" required>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t<br>\n");
      out.write("\t\t\t\t<button class=\"btn btn-lg btn-primary btn-block btn-signin\" id=\"IngresoLog\" type=\"submit\">Crear cuenta</button>\n");
      out.write("\t</form>\n");
      out.write("\t</div>\t\n");
      out.write("\t\t </div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
