/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.17
 * Generated at: 2019-05-07 14:10:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class LoginView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/Users/xiaoluo/eclipse-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ISST-19-CRIS/WEB-INF/lib/standard-1.1.2.jar!/META-INF/fn.tld", Long.valueOf(1098703890000L));
    _jspx_dependants.put("jar:file:/Users/xiaoluo/eclipse-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ISST-19-CRIS/WEB-INF/lib/shiro-web-1.4.0.jar!/META-INF/shiro.tld", Long.valueOf(1494006348000L));
    _jspx_dependants.put("/WEB-INF/lib/shiro-web-1.4.0.jar", Long.valueOf(1553598958492L));
    _jspx_dependants.put("jar:file:/Users/xiaoluo/eclipse-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ISST-19-CRIS/WEB-INF/lib/standard-1.1.2.jar!/META-INF/c.tld", Long.valueOf(1098703890000L));
    _jspx_dependants.put("/WEB-INF/lib/standard-1.1.2.jar", Long.valueOf(1553598963966L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Login View</title>\r\n");
      out.write("<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\" integrity=\"sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u\" crossorigin=\"anonymous\">\r\n");
      out.write("<!-- Temas-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css\" integrity=\"sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp\" crossorigin=\"anonymous\">\r\n");
      out.write("</head>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("body {\r\n");
      out.write("\tbackground-image:\r\n");
      out.write("\t\turl('https://image.jimcdn.com/app/cms/image/transf/none/path/sc77e1e58a42c514a/image/i9977c7b3a6db203a/version/1516578954/image.jpg');\r\n");
      out.write("\tbackground-size: cover;\r\n");
      out.write("\tfont: normal normal 16px quicksand; \r\n");
      out.write("\tletter-spacing: 1px;\r\n");
      out.write("\t\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\ttext-transform: uppercase;\r\n");
      out.write("    background-position: center;\r\n");
      out.write("    background-repeat: no-repeat;\r\n");
      out.write("    overflow-x: hidden;\r\n");
      out.write("    padding-top: 20px;\r\n");
      out.write("    z-index: 1;\r\n");
      out.write("    top: 0;\r\n");
      out.write("    left: 0;\r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write("/**\r\n");
      out.write(" * se aplica el ancho, margen centrado\r\n");
      out.write(" * borde de un pixel con redondeado, y rellenado\r\n");
      out.write(" * a la izquierda y derecha\r\n");
      out.write(" */\r\n");
      out.write("#Contenedor{\r\n");
      out.write("\twidth: 400px;\r\n");
      out.write("\tmargin: 50px auto;\r\n");
      out.write("\tbackground-color: #F3EDED;\r\n");
      out.write("        border: 15px solid #ECE8E8;\r\n");
      out.write("\theight: 200px;\r\n");
      out.write("\tborder-radius:8px;\r\n");
      out.write("\tpadding: 0px 9px 0px 9px;\r\n");
      out.write("}\r\n");
      out.write(" \r\n");
      out.write("/**\r\n");
      out.write(" * Aplicando al icono de usuario el color de fondo,\r\n");
      out.write(" * rellenado de 20px y un redondeado de 120px en forma\r\n");
      out.write(" * de un circulo\r\n");
      out.write(" */\r\n");
      out.write(".Icon span{\r\n");
      out.write("      background: #A8A6A6;\r\n");
      out.write("      padding: 20px;\r\n");
      out.write("      border-radius: 120px;\r\n");
      out.write("}\r\n");
      out.write("/**\r\n");
      out.write(" * Se aplica al contenedor madre un margen de tamaño 10px hacia la cabecera y pie,\r\n");
      out.write(" * color de fuente blanco,un tamaño de fuente 50px y texto centrado.\r\n");
      out.write(" */\r\n");
      out.write(".Icon{\r\n");
      out.write("     margin-top: 10px;\r\n");
      out.write("     margin-bottom:10px; \r\n");
      out.write("     color: #FFF;\r\n");
      out.write("     font-size: 50px;\r\n");
      out.write("     text-align: center;\r\n");
      out.write("}\r\n");
      out.write("/**\r\n");
      out.write(" * Se aplica al contenedor donde muestra en el pie\r\n");
      out.write(" * la opción de olvidaste tu contraseña?\r\n");
      out.write(" */\r\n");
      out.write(".opcioncontra{\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tmargin-top: 20px;\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("}\r\n");
      out.write("h1 {\r\n");
      out.write("text-align: center;\r\n");
      out.write("padding: 13vh;\r\n");
      out.write("  font-weight: normal;\r\n");
      out.write("  font-size: 40px;\r\n");
      out.write("  font-family: 'Lobster';\r\n");
      out.write("  text-transform: uppercase;    \r\n");
      out.write("}\r\n");
      out.write("div {\r\n");
      out.write("\tfont-size: medium;\r\n");
      out.write("\tfont-family: Times New Roman;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("button {\r\n");
      out.write("border: 2px solid #b5f2f2;  /*borde: estilo y color*/\r\n");
      out.write("font: normal normal 18px quicksand;  /*fuente*/\r\n");
      out.write("letter-spacing: 2px; /*separación entre las letras*/\r\n");
      out.write("text-align: center; /*alineación del texto*/\r\n");
      out.write("text-transform: uppercase; /*texto se transforma en mayúsculas*/\r\n");
      out.write("padding: 10px;  /*tamaño del fondo*/\r\n");
      out.write("border-radius: 30px 0px 30px 0px; /*ángulos de las 4 esquinas del borde/fondo*/\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "NavBar.jsp", out, false);
      out.write("\r\n");
      out.write("\t<h1>Bienvenido a eCV</h1>\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<p>\r\n");
      out.write("\t\tCon nosotros el trabajo de tus sueños estará más cerca.\r\n");
      out.write("\t\t<p>\r\n");
      out.write("\t\tDiseña tu propio currículum personalizado o rellena una plantilla para tu empresa.\r\n");
      out.write("\t\t<p>\r\n");
      out.write("\t\tAccede a tu cuenta o regístrate para empezar.\r\n");
      out.write("\t\t\r\n");
      out.write("\t    <form action=\"LoginServlet\" method=\"post\">\r\n");
      out.write("\t    <div id=\"Contenedor\">\r\n");
      out.write("<div class=\"ContentForm\">\r\n");
      out.write("\t\t\t<form action=\"\" method=\"post\" name=\"FormEntrar\">\r\n");
      out.write("\t\t \t\t<div class=\"input-group input-group-lg\">\r\n");
      out.write("\t\t\t\t  <span class=\"input-group-addon\" id=\"sizing-addon1\"><i class=\"glyphicon glyphicon-envelope\"></i></span>\r\n");
      out.write("\t\t\t\t  <input type=\"email\" class=\"form-control\" name=\"correo\" placeholder=\"Correo\" id=\"Correo\" aria-describedby=\"sizing-addon1\" required>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t\t<div class=\"input-group input-group-lg\">\r\n");
      out.write("\t\t\t\t  <span class=\"input-group-addon\" id=\"sizing-addon1\"><i class=\"glyphicon glyphicon-lock\"></i></span>\r\n");
      out.write("\t\t\t\t  <input type=\"password\" name=\"cons\" class=\"form-control\" placeholder=\"******\" aria-describedby=\"sizing-addon1\" required>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t\t<button class=\"btn btn-lg btn-primary btn-block btn-signin\" id=\"IngresoLog\" type=\"submit\">Login</button>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t </div>\t\r\n");
      out.write("\t\t </div>\r\n");
      out.write("\t\t<a href=\"SignUp.jsp\">Registrarse</a></div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
